
export default {
  board_now: "/board/now",
  board_later: "/board/later",
  home: "/home",
  details: "/details",
  gallery: "/gallery",
  driver_profile: "/driver/profile",
  all_reviews: "/reviews",
  payment: "/payment",
  cart: "/cart",
  payment_success: "/payment/confirm",
  ticket: "/ticket",
  ride: "/ride",
  ride_list: "/rides",
  ride_detail: "/rides/detail",
  later_search: "/later/search",
  contact: "/contact",
  favourite: "/favourite",
  chats: "/chats",
  ticketView: "/ticketView",
  user_profile: "/user/profile",

  APP_USERS: "/app/users",

  CUSTOMERS_CUSTOMER: "/app/users/customers/customer/",
  CUSTOMERS_MANUFACTURES: "/app/users/customers/manufacturer/",
  PROFILE:"/profile",
  USER_PROFILE:"/admin/users/edit/",
  USER_PROFILE_CREATE: "/admin/users/create/",
  HUB_MASTERS: "/hub/master",
  TASK_DETAIL: "/task/detail/",
  SERVICE_DETAIL: "/service/detail/",

  ADMIN_USER:"/admin/users",
  ADMIN_USER_CREATE:"/users/create",
  ADMIN_USER_UPDATE:"/users/update/",
  USER_UPDATE_MY_PROFILE:"/users/updatemyprofile/",
  CALENDAR:"/calendar",
  
  ROLE:"/roles",
  ROLE_CREATE:"/role/create",
  ROLE_CREATE_UPDATE:"/role/update/",
  ROLE_DETAIL:"/role/details/",
  BLOGS_CREATE:"/blogs/create",
  BLOGS_UPDATE:"/blogs/update/",
  PRODUCT_DETAILS:"/product/details/",
  PRODUCT_CREATE:"/product/create",
  NOTIFICATION_DETAILS:"/notifications",
  CONTACT_LIST: "/contact",
  CONTACT_CREATE: "/contact/create"
};
